### LAYOUT
enabled_layouts splits,stack
### LAYOUT

### INPUT_METHOD
env GLFW_IM_MODULE=ibus
### INPUT_METHOD

### CURSOR
cursor_shape block
cursor_blink_interval 0.5
cursor #3A5B7E
cursor_text_color background
### CURSOR

### TEXT
adjust_line_height -1
adjust_baseline -5
adjust_column_width 0
### TEXT

### REMOTE_SSH
allow_remote_control yes
allow_remote_control yes
shell_integration enabled
shell_integration no-cursor
### REMOTE_SSH

### CLIPBOARD
clipboard_control write-clipboard write-primary read-clipboard read-primary
### CLIPBOARD

# KITTY_FONTS
font_family      family="Consolas ligaturized v3"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 25
# KITTY_FONTS

# AUTO_SESSION
startup_session ~/.config/kitty/sessions/last.kitty-session
# AUTO_SESSION

### MAPPING
map f11 toggle_fullscreen
map ctrl+shift+s save_as_session --use-foreground-process --save-only ~/.config/kitty/sessions/last.kitty-session
# map ctrl+c copy_to_clipboard selection
# map ctrl+v paste_from_clipboard
### MAPPING
