local dap = require("dap")

vim.keymap.set("n", "<F5>", require("dap").continue, { desc = "Debug: Continue" })
vim.keymap.set("n", "<F10>", require("dap").step_over, { desc = "Debug: Step Over" })
vim.keymap.set("n", "<F11>", require("dap").step_into, { desc = "Debug: Step Into" })
vim.keymap.set("n", "<F9>", require("dap").toggle_breakpoint, { desc = "Debug: Toggle Breakpoint" })
-- vim.keymap.set("n", "<F6>", function()
-- 	require("dap").continue()
-- end, { desc = "Debug: Start/Continue" })
-- vim.keymap.set("n", "<F10>", function()
-- 	require("dap").step_over()
-- end, { desc = "Debug: Step Over" })
-- vim.keymap.set("n", "<F11>", function()
-- 	require("dap").step_into()
-- end, { desc = "Debug: Step Into" })
-- vim.keymap.set("n", "<F12>", function()
-- 	require("dap").step_out()
-- end, { desc = "Debug: Step Out" })
-- vim.keymap.set("n", "<leader>db", function()
-- 	require("dap").toggle_breakpoint()
-- end, { desc = "Debug: Toggle Breakpoint" })
-- vim.keymap.set("n", "<leader>dB", function()
-- 	require("dap").set_breakpoint(vim.fn.input("Breakpoint condition: "))
-- end, { desc = "Debug: Set Conditional Breakpoint" })
-- vim.keymap.set("n", "<leader>dr", function()
-- 	require("dap").repl.open()
-- end, { desc = "Debug: Open REPL" })
-- vim.keymap.set("n", "<leader>dl", function()
-- 	require("dap").run_last()
-- end, { desc = "Debug: Run Last" })
