-- map group --
return {
	{ "<leader>a", group = "AI", mode = { "n", "x" } },
	{ "<leader>b", group = "Buffer" },
	{ "<leader>d", group = "Debug" },
	{ "<leader>D", group = "Database" },
	{ "<leader>e", group = "File picker" },
	{ "<leader>f", group = "Telescope extension", mode = { "n", "x" } },
	{ "<leader>g", group = "Git" },
	{ "<leader>gh", group = "Github" },
	{ "<leader>ghi", group = "Issues" },
	{ "<leader>ghc", group = "Commits" },
	{ "<leader>ghl", group = "Litee" },
	{ "<leader>ghp", group = "Pull Request" },
	{ "<leader>ghr", group = "Review" },
	{ "<leader>ght", group = "Threads" },
	{ "<leader>m", group = "Code map" },
	{ "<leader>p", group = "Pin" },
	{ "<leader>P", group = "Projects" },
	{ "<leader>r", group = "Refactor", mode = { "n", "x" } },
	{ "<leader>R", group = "Rest API (only ft=http)" },
	{ "<leader>s", group = "Search & Replace", mode = { "n", "x" } },
	{ "<leader>S", group = "Session" },
	{ "<leader>u", group = "Unset" },
	{ "<leader>x", group = "Diagnostics" },
	{ "<leader>y", group = "Launchers" },
	{ "<leader><tab>", group = "Tab" },
	{ "<leader>w", group = "Window" },
}
